### ISSUE TITLE
Newbie intellij IDE question

### ISSUE THREAD

**Issue by KG-ethc** [fpinjava/fpinjava#11]
I have never used JUnit/Gradle before and carely know my way around the IntelliJ IDE. I keep getting this error trying to run the tests: 

"Error:Unable to make the module: fpinjava-parent, related gradle configuration was not found. Please, re-import the Gradle project and try again."

I have no idea how to fix this, makes it hard to play around with the exercises. Sometimes when I try to edit the test config it says JUnit not found in project....

![image](https://user-images.githubusercontent.com/26746602/31849676-0a55a556-b5fb-11e7-96f2-a0675917b396.png)

**Comment by pysaumont** [comment]
Hi,

Did you import the project by selecting New > Project from existing sources, then selecting the fpinjava-parent directory, clicking OK and selecting Import project from external model > Gradle?

If you did so, you should have a "Gradle" button on the right edge of the window. 

Clicking this button should open the Gradle project pane, where you can click a button to Refresh all Gradel project (leftmost button at the top of the pane).

If this does not work, You IntelliJ might not be configured correctly for Gradle. Open the Settings dialog box by selecting Settings in the File menu. Select Build, Execution, Deployment, then Build Tools then Gradle. Verify that the Use default Gradle wrapper option is checked.

If it is checked and it still does not work, try the second option (Use Gradle wrapper task configuration). If this does not work either, you should download a copy of Gradle, install it on your computer, select Use Gradle local distribution and set the Gradle Home option to the directory where you have installed Gradle.

**Comment by KG-ethc** [comment]
Thank you that was helpful, now the problem is that JUnit.Test cannot be resolved. If I comment out the line it builds and compiles successfully, but now I don't know how to run my tests...

![image](https://user-images.githubusercontent.com/26746602/31877278-b5f72732-b78a-11e7-9ddf-14a5b62c15f0.png)

**Comment by pysaumont** [comment]
Each module (in the build.gradle file) contains the following line:

testCompile group: 'junit', name: 'junit', version: '4.+'

This should cause Gradle to load the JUnit jar.

Look in the Project pane (on the left). The last element should be "External Libraries". If you unfold this element, you should see JUnit. If not, you should get an error message each time youy refresh Gradle (top left button in the Gradle pane). The error message should be displayed in the status bar and you can have more info by clicking on it. It should say what prevented the download of JUnit.

This said, there is a workaround because IntelliJ has it's own copy of JUnit, and is also able to download it. Open a test class. You should get an IntelliJ error on each call to JUnit. Click on one of the error source, for example a JUnit import, or a JUnit annotation. A red light bulb should be displayed. Cilcking on this light bulb should display several options, among which you can chose between using IntelliJ Junit version or downloading a copy from MVN repository.

**Comment by KG-ethc** [comment]
Thanks so much, I think it's working correctly now. If you're ever in San Jose, CA you can have a pizza on me :)
